DROP TABLE IF EXISTS "auteur";
DROP TABLE IF EXISTS "oeuvre";
DROP TABLE IF EXISTS "livre";
DROP TABLE IF EXISTS "magazine";
DROP TABLE IF EXISTS "exemplaire";
DROP TABLE IF EXISTS "usager";
DROP TABLE IF EXISTS "emprunt";
DROP TABLE IF EXISTS "reservation";

ALTER TABLE livre ADD FOREIGN KEY (auteur) REFERENCES auteur(id) ON UPDATE CASCADE
ALTER TABLE exemplaire ADD FOREIGN KEY (oeuvre) REFERENCES oeuvre(id) ON UPDATE CASCADE